services:
  # example
  # challenge_name:
  #  build: ./web/challenge_name/src
  #  ports:
  #    - "9000:9000"
  #  restart: on-failure
  # networks:
  #    - nginx_network

  mastermind:
    build: ./misc/mastermind/src
    ports:
      - "4444:4444"
    restart: on-failure
  
  noob1:
    build: ./noob/noob1/src
    ports:
      - "6000:22"
    restart: on-failure

  noob2:
    build: ./noob/noob2/src
    ports:
      - "6001:22"
    restart: on-failure
  
  noob3:
    build: ./noob/noob3/src
    ports:
      - "6002:22"
    restart: on-failure
  
  noob4:
    build: ./noob/noob4/src
    ports:
      - "6003:22"
    restart: on-failure

  noob5:
    build: ./noob/noob5/src
    ports:
      - "6004:22"
    restart: on-failure

  commlink:
    build: ./pwn/commlink/src
    ports:
      - "9000:9000"
    restart: on-failure

  sc0:
    build: ./pwn/sc0/src
    ports:
      - "9001:9001"
    restart: on-failure

networks:
  nginx_network:
    external: true
