
# Port 80 and 443 are reserved for the nginx container and should not be used for challenges.
# Available port ranges:
## rev: 5xxx
## noob: 6xxx
## crypto: 7xxx
## web: 8xxx
## pwn: 9xxx
## misc: 10xxx

services:
  # example
  # challenge_name:
  #  build: ./web/challenge_name/src
  #  ports:
  #    - "9000:9000"
  #  restart: on-failure
  # networks:
  #    - nginx_network

  # rev 5xxx


  # noob 6xxx
  noob1:
    build: ./noob/noob1/src
    ports:
      - "6000:22"
    restart: on-failure

  noob2:
    build: ./noob/noob2/src
    ports:
      - "6001:22"
    restart: on-failure

  noob3:
    build: ./noob/noob3/src
    ports:
      - "6002:22"
    restart: on-failure

  noob4:
    build: ./noob/noob4/src
    ports:
      - "6003:22"
    restart: on-failure

  noob5:
    build: ./noob/noob5/src
    ports:
      - "6004:22"
    restart: on-failure
  
  # web 8xxx
  # note web challenges requiring https should map ports,
  # the ports must be mapped in the nginx.conf file
  # use big_picture as an example
  big_picture:
    build: ./web/big_picture/src
    # ports:
      # - "8001:8080"
    restart: on-failure
    networks:
      - nginx_network

  mastermind:
    build: ./misc/mastermind/src
    ports:
      - "10444:4444"
    restart: on-failure
  # pwn 9xxx
  commlink:
    build: ./pwn/commlink/src
    ports:
      - "9000:9000"
    restart: on-failure

  sc0:
    build: ./pwn/sc0/src
    ports:
      - "9001:9001"
    restart: on-failure

networks:
  nginx_network:
    external: true
