# docker-compose.yml
# Challenge port ranges:
# rev: 5xxx
# noob: 6xxx
# crypto: 7xxx
# web: 8xxx
# pwn: 9xxx
# misc: 10xxx

# This empty compose file uses the 'include' feature to load all the category-specific compose files
include:
  - ./compose/infra.yml
  - ./compose/web.yml
  - ./compose/noob.yml
  - ./compose/pwn.yml
  - ./compose/misc.yml
  - ./compose/rev.yml
