[package]
name = "cross-eyed"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = "1.0.15"
# headless_chrome = { git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = [
#     "fetch",
# ] }
rand = "0.9.0"
rocket = "0.5.1"
serde_json = "1.0.139"
