# infra/promtail/config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets:
          - localhost
        labels:
          job: caddy
          __path__: /var/log/caddy/*log
    pipeline_stages:
      - match:
          selector: '{job="caddy"}'
          stages:
            - regex:
                expression: '(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) (?P<remote_ip>\S+) - (?P<user>\S+) \[(?P<time_local>[^\]]*)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
            - labels:
                remote_ip:
                method:
                path:
                protocol:
                status:

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth
          __path__: /var/log/system/auth.log*
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - labels:
          stream:
