services:
  # loki:
  #   image: grafana/loki:latest
  #   volumes:
  #     - ../infra/loki/config.yaml:/etc/loki/config.yaml:ro
  #     - loki_data:/loki
  #   restart: unless-stopped
  #   command: -config.file=/etc/loki/config.yaml -config.expand-env
  #   networks:
  #     - log

  # promtail:
  #   image: grafana/promtail:latest
  #   volumes:
  #     - ../infra/promtail/config.yml:/etc/promtail/config.yml:ro
  #     - /var/log:/var/log/system:ro
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - caddy_log:/var/log/caddy:ro
  #   command: -config.file=/etc/promtail/config.yml
  #   depends_on:
  #     - loki
  #   restart: unless-stopped
  #   networks:
  # - log

  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: node_exporter
  #   command:
  #     - "--path.rootfs=/host"
  #   network_mode: host
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - "/:/host:ro,rslave"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    networks:
      - log

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ../infra/grafana/provisioning:/etc/grafana/provisioning
      - ../infra/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=uithack
      - GF_SECURITY_ADMIN_PASSWORD=grafana-admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped
    networks:
      - log

volumes:
  prometheus_data:
  loki_data:
  grafana_data:
  caddy_log:
    external: true

networks:
  log:
    external: true
