# Dockerfile
FROM nginx:alpine

LABEL description="!big_picture challenge"
LABEL category="web"
LABEL source="UiTHack25"
LABEL version="1.0"

# Copy nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy web content
COPY index.html /usr/share/nginx/html/

# Set permissions
RUN chown -R nginx:nginx /usr/share/nginx/html/

# Insert other logic here

# Port ranges:
## rev: 5xxx
## noob: 6xxx
## crypto: 7xxx
## web: 8xxx
## pwn: 9xxx
## misc: 10xxx
EXPOSE 8080

# Default command
CMD ["nginx", "-g", "daemon off;"]

# Remember to add the the container in the docker-compose.yml file!
# docker build -t big_picture .
# docker run -dp 8001:8080 -it --rm big_picture